const services = [
    {
      id: "bathroom-remodeling",
      title: "Bathroom Remodeling",
      shortDescription: "Complete bathroom transformation services with premium materials and expert craftsmanship.",
      longDescription: "Our bathroom remodeling services transform outdated spaces into beautiful, functional areas that reflect your personal style. We handle everything from design to installation, using premium stone materials and the latest techniques to ensure a stunning result that increases your home's value.",
      features: [
        "Custom design consultations",
        "Premium selection",
        "Fixture upgrades and replacements",
        "Lighting improvements",
        "Flooring installation",
        "Waterproofing and moisture control",
      ],
      benefits: [
        "Increased home value",
        "Enhanced functionality",
        "Improved energy efficiency",
        "Better use of space",
        "Modern aesthetic appeal",
      ],
      imageSrc: "https://stoneworksremodlling.s3.ap-south-1.amazonaws.com/webp/NctOfmDbqGoQGM2Qm9a8C.webp",
      imageAlt: "Luxury bathroom remodel in Metro Detroit, MI by Stone Works Remodeling",
      icon: "✨",
    },
    {
      id: "shower-conversions",
      title: "Tub-to-Shower Conversions",
      shortDescription: "Modern shower solutions that maximize space and accessibility.",
      longDescription: "Our tub-to-shower conversion service transforms your outdated bathtub into a stylish, accessible shower. Perfect for homeowners looking to update their bathroom's functionality while creating a more contemporary aesthetic. Our conversions are completed quickly and with minimal disruption to your home.",
      features: [
        "Custom shower designs",
        "Stone and tile options",
        "Glass door installations",
        "Accessibility features",
        "Rapid installation process",
        "Water-saving fixtures",
      ],
      benefits: [
        "Improved accessibility",
        "Easier cleaning and maintenance",
        "Modern appearance",
        "Space optimization",
        "Water conservation",
      ],
      imageSrc: "https://stoneworksremodlling.s3.ap-south-1.amazonaws.com/webp/i5a_set3C7bnEDegPuZld.webp",
      imageAlt: "Modern shower conversion in Metro Detroit, MI by Stone Works Remodeling",
      icon: "🚿",
    },
    {
      id: "walk-in-tubs",
      title: "Walk-In Tub Installation",
      shortDescription: "Safety-focused bathroom solutions that don't compromise on luxury.",
      longDescription: "Our walk-in tub installations combine safety and luxury to create accessible bathing experiences for people of all abilities. These specialized tubs feature easy entry, comfortable seating, and therapeutic options like hydrotherapy jets. Perfect for aging in place or anyone with mobility concerns.",
      features: [
        "Low threshold entry doors",
        "Anti-slip flooring",
        "Built-in seating",
        "Hydrotherapy options",
        "Fast-fill and drain technology",
        "ADA compliant designs",
      ],
      benefits: [
        "Enhanced safety",
        "Independent bathing",
        "Therapeutic benefits",
        "Comfort and relaxation",
        "Aging-in-place solution",
      ],
      imageSrc: "https://stoneworksremodlling.s3.ap-south-1.amazonaws.com/webp/krY1iLp90R9l3kcrrUhu-.webp",
      imageAlt: "Accessible walk-in tub installation in Metro Detroit, MI by Stone Works Remodeling",
      icon: "🛁",
    },
    {
      id: "stone-countertops",
      title: "Stone Countertop Installation",
      shortDescription: "Beautiful, durable surfaces for bathrooms and kitchens.",
      longDescription: "Our countertop installation service brings elegance and durability to your bathroom or kitchen. We offer a wide selection of premium natural and engineered stone options, including granite, marble, quartz, and more. Each installation is precisely measured and expertly fitted for a flawless finish.",
      features: [
        "Custom measurements and templates",
        "Wide selection of materials",
        "Expert fabrication and finishing",
        "Sink and fixture coordination",
        "Sealing and maintenance education",
        "Backsplash options",
      ],
      benefits: [
        "Exceptional durability",
        "Increased home value",
        "Heat resistance",
        "Unique natural patterns",
        "Timeless elegance",
      ],
      imageSrc: "https://stoneworksremodlling.s3.ap-south-1.amazonaws.com/webp/Gemini_Generated_Image_7bprdt7bprdt7bpr.webp",
      imageAlt: "Stone countertop installation in Metro Detroit, MI by Stone Works Remodeling",
      icon: "💎",
    },
    {
      id: "custom-works",
      title: "Custom Works",
      shortDescription: "Bespoke bathroom remodeling tailored to your unique vision and style.",
      longDescription: "Our custom works service creates one-of-a-kind bathrooms that reflect your personal taste and lifestyle. From luxurious spa-inspired retreats to minimalist modern designs, we collaborate with you to craft a space that’s uniquely yours, using premium materials and expert craftsmanship.",
      features: [
        "Personalized design consultations",
        "Custom stone and tile work",
        "Unique fixture and lighting solutions",
        "Innovative space planning",
        "High-end material selection",
        "Tailored accessibility features",
      ],
      benefits: [
        "Fully customized design",
        "Premium quality craftsmanship",
        "Enhanced home value",
        "Unique aesthetic appeal",
        "Personalized functionality",
      ],
      imageSrc: "https://stoneworksremodlling.s3.ap-south-1.amazonaws.com/youll-want-switch-walk-in-shower-3984666-hero-cfb9cafaf16d4b398e0d1401d3b7a516.webp",
      imageAlt: "Custom bathroom remodeling by Stone Works Remodeling in Metro Detroit, MI",
      icon: "🎨",
      customProjects: [
        {
          id: "spa-retreat",
          title: "Spa-Inspired Master Bathroom",
          description:
            "A luxurious master bathroom with custom marble vanities, a freestanding soaking tub, and intricate mosaic tile work, creating a serene spa-like retreat.",
          imageSrc: "https://stoneworksremodlling.s3.ap-south-1.amazonaws.com/2da00bfadabbfcaca1ce0e54d812e1b3.webp",
          imageAlt: "Spa-inspired master bathroom by Stone Works Remodeling in Metro Detroit, MI",
        },
        {
          id: "modern-minimalist",
          title: "Modern Minimalist Bathroom",
          description:
            "A sleek, minimalist bathroom featuring custom-cut quartz countertops, frameless glass shower, and integrated LED lighting for a clean, contemporary look.",
          imageSrc: "https://stoneworksremodlling.s3.ap-south-1.amazonaws.com/251d1ac7e6d8476ddcbdb0c7de73209d.webp",
          imageAlt: "Modern minimalist bathroom by Stone Works Remodeling in Metro Detroit, MI",
        },
        {
          id: "accessible-elegance",
          title: "Accessible Elegance",
          description:
            "A custom bathroom with a spacious walk-in shower, ADA-compliant fixtures, and elegant stone finishes, blending accessibility with luxury.",
          imageSrc: "https://stoneworksremodlling.s3.ap-south-1.amazonaws.com/youll-want-switch-walk-in-shower-3984666-hero-cfb9cafaf16d4b398e0d1401d3b7a516.webp",
          imageAlt: "Accessible custom bathroom by Stone Works Remodeling in Metro Detroit, MI",
        },
      ],
      testimonials: [
        {
          id: 1,
          name: "Sarah M.",
          location: "Metro Detroit, MI",
          quote:
            "Stone Works Remodeling turned our outdated bathroom into a custom masterpiece. The attention to detail and personalized design process were exceptional!",
          rating: 5,
          project: "Spa-Inspired Master Bathroom",
        },
        {
          id: 2,
          name: "James T.",
          location: "Metro Detroit, MI",
          quote:
            "Their custom work exceeded our expectations. The minimalist design and high-quality materials transformed our bathroom into a modern oasis.",
          rating: 5,
          project: "Modern Minimalist Bathroom",
        },
      ],
      processSteps: [
        {
          step: 1,
          title: "Vision Consultation",
          description: "We discuss your ideas, preferences, and budget to create a tailored design plan.",
          icon: "💡",
        },
        {
          step: 2,
          title: "Custom Design",
          description: "Our team crafts a unique design with premium materials and innovative layouts.",
          icon: "✏️",
        },
        {
          step: 3,
          title: "Expert Installation",
          description: "Skilled craftsmen execute the project with precision and minimal disruption.",
          icon: "🔨",
        },
        {
          step: 4,
          title: "Final Reveal",
          description: "We unveil your custom bathroom, ensuring every detail meets your expectations.",
          icon: "🎉",
        },
      ],
    },
  ];
  
  export default services;